### ISSUE TITLE
scorer.py contains hard-wired platform-specific paths

### ISSUE THREAD

**Issue by popey** [rajtilakjee/simone#7]
👋  Hello, and thanks for making simone. 🙏 

**Describe the bug**

Running simone on a mac fails due to https://github.com/rajtilakjee/simone/blob/main/src/utils/scorer.py#L15 pointing `pytesseract.pytesseract.tesseract_cmd` at `C:/Program Files/Tesseract-OCR/tesseract.exe` which is never going to work. On my mac, using homebrew, the tesseract binary is in `/opt/homebrew/bin/tesseract`, but this may vary.

I have successfully tested simone by replacing that line as appropriate for my platform, and it works. Nice one!

```bash
python src/main.py
Enter YouTube URL: https://www.youtube.com/watch?v=VDIAHEoECfM
/Users/alan/Work/rajtilakjee/simone/.venv/lib/python3.12/site-packages/whisper/transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Traceback (most recent call last):
  File "/Users/alan/Work/rajtilakjee/simone/.venv/lib/python3.12/site-packages/pytesseract/pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Program Files/Tesseract-OCR/tesseract.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alan/Work/rajtilakjee/simone/src/main.py", line 47, in <module>
    blogpost(url)
  File "/Users/alan/Work/rajtilakjee/simone/src/main.py", line 39, in blogpost
    score = scores.score_frames()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Work/rajtilakjee/simone/src/utils/scorer.py", line 20, in score_frames
    extracted_text = pytesseract.image_to_string(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Work/rajtilakjee/simone/.venv/lib/python3.12/site-packages/pytesseract/pytesseract.py", line 423, in image_to_string
    return {
           ^
  File "/Users/alan/Work/rajtilakjee/simone/.venv/lib/python3.12/site-packages/pytesseract/pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/Work/rajtilakjee/simone/.venv/lib/python3.12/site-packages/pytesseract/pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "/Users/alan/Work/rajtilakjee/simone/.venv/lib/python3.12/site-packages/pytesseract/pytesseract.py", line 260, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: C:/Program Files/Tesseract-OCR/tesseract.exe is not installed or it's not in your PATH. See README file for more information.

```

**To Reproduce**
1. Use a mac running macOS
2. `brew install ffmpeg tesseract virtualenv`
3. Put API key in `.env`
4. `pip install -r requirements.txt`
5. `python src/main.py`
6. Paste a YouTube url such as https://www.youtube.com/watch?v=VDIAHEoECfM

**Expected behavior**

I don't know, but I assume it makes a blog post :) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma on an M3 MacBook Pro

**Comment by rajtilakjee** [comment]
Hi @popey I don't have a Mac with me, only a Windows 11 laptop. I was doing a bit of research online to find a suitable solution that can make it work across all platforms. So far, I have found 2 options which I have not tried myself; Docker, and PyInstaller. Do you have any experience shipping products like this?

**Comment by popey** [comment]
Hey @rajtilakjee thanks for the quick response.

I'm no expert on this stuff. Doing a bit of googling it looks like this is a known issue with tesseract, that you have to point to the binary.

I don't think this is necessarily a packaging issue to be honest. I had no problem running this from a terminal - as I expect many other nerds might.

However, you might want to detect the OS and set the path accordingly. 

Further, just put a note in the README.md and docs to highlight that (until this issue is fixed), new users will need to tweak the path. It's not a massive deal, in my opinion.

**Comment by sjamaan** [comment]
It would make sense to expect the user to have the binary in their PATH, so to simply invoke `tesseract` without a full path (or extension). On most unix-likes that would be trivial, but on Windows that requires some atypical messing about with the control panel system tool.

If in doubt, provide a command-line switch to point to the correct binary to use, perhaps with a config file so you don't have to use the argument every single time.

Maybe try invoking it without a path first and then fall back to scanning some common locations, and failing if none were found?

**Comment by popey** [comment]
You could also use `sys.platform` to detect the OS, and then use `/usr/bin/env tesseract` on *nix systems (macOS and Linux and I guess BSD ;)), and a different path for windows.

**Comment by rajtilakjee** [comment]
@sjamaan Will try some of the pointers you mentioned in your suggestion. A probable solution which is a quick fix is found in SO. For now, I will update the documentation with this info. Next, I will try either your or @popey's suggestion of using `sys.platform` to specify the path depending on the system. I am keeping the issue open for now till I fix the issue by today evening. Once again, thank you @popey and @sjamaan for taking the time out to make Simone better.
